# Listing 3.6: lathe.rb
# Access the Entities object
model = Sketchup.active_model
ents = model.entities
# Create the 2-D shape
curve = ents.add_curve [0, 0, 1.244209], [0.116554, 0, 1.238382],
    [0.160261, 0, 1.217985], [0.186486, 0, 1.188846],
    [0.1894, 0, 1.165536], [0.17483, 0, 1.145139],
    [0.142778, 0, 1.127656], [0.096157, 0, 1.118914],
    [0.093243, 0, 1.063551], [0.175152, 0, 0.996269],
    [0.175152, 0, 0.915269], [0.28237, 0, 0.871026],
    [0.375392, 0, 0.801741], [0.448486, 0, 0.711683],
    [0.497151, 0, 0.606398], [0.51839, 0, 0.492371],
    [0.510894, 0, 0.376625], [0.475126, 0, 0.26629],
    [0.413287, 0, 0.168161], [0.329188, 0, 0.088283],
    [0.228007, 0, 0.031575], [0.115978, 0, 0.001531],
    [0, 0, 0], [0, 0, 1.244209]
    
curve_face = ents.add_face curve

# Create the circular path
path = ents.add_circle [0, 0, 0], [0, 0, 1], 2

# Create the figure
curve_face.followme path
